import { useEffect, useState } from "react";
import RevealOnScroll from "./RevealOnScroll";
import SectionHeading from "./SectionHeading";
const API = import.meta.env.VITE_API_URL || "http://localhost:5000/api/v1";
const fallback = { title: "Two disciplines, one engineer", intro: "I’m a Computer Science & Engineering student working full-stack on the MERN stack while maintaining a parallel interest in embedded systems and hardware.", details: "I like projects where both sides meet: real-time dashboards talking to real sensors, and APIs serving real-world data.", toolchain: [["frontend", "React, Tailwind"], ["backend", "Node.js, Express, MongoDB"], ["embedded", "ESP32, Arduino, C/C++"]].map(([label, value]) => ({ label, value })) };
export default function About() {
  const [about, setAbout] = useState(fallback);
  useEffect(() => { let active = true; const load = () => fetch(`${API}/about`).then((res) => res.json()).then((data) => active && data.data && setAbout(data.data)).catch(() => {}); load(); const timer = setInterval(load, 30000); return () => { active = false; clearInterval(timer); }; }, []);
  return <section id="about" className="border-t border-line py-24"><div className="mx-auto max-w-6xl px-6"><RevealOnScroll><SectionHeading index="01" subtitle="about" title={about.title || fallback.title} /></RevealOnScroll><div className="grid gap-10 md:grid-cols-2"><RevealOnScroll delay={0.05}><p className="leading-8 text-ink-dim">{about.intro || fallback.intro}</p><p className="mt-4 leading-8 text-ink-dim">{about.details || fallback.details}</p></RevealOnScroll><RevealOnScroll delay={0.15}><div className="rounded-lg border border-line bg-surface p-6 font-mono text-sm"><p className="mb-3 text-ink-muted">{"// core toolchain"}</p>{(about.toolchain?.length ? about.toolchain : fallback.toolchain).map((item) => <div key={item.label} className="flex flex-col gap-x-3 border-b border-line-soft py-2 last:border-0 sm:flex-row sm:items-baseline"><span className="w-24 shrink-0 text-copper">{item.label}:</span><span className="text-ink-dim">{item.value}</span></div>)}</div></RevealOnScroll></div></div></section>;
}
